import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "./Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen flex">
          <div className="flex-initial w-14 h-full min-w-[56px] bg-slate-800">
            <Navbar />
          </div>
          <div className="flex-auto bg-gray-100 text-black">{children}</div>
        </div>
      </body>
    </html>
  );
}
